sudo: yes
dist: xenial

language: python
python:
  - "3.7"

branches:
  only:
    - master

addons:
  apt:
    packages:
      # needed by Doxygen to make graphs
      - graphviz

# Install Doxygen manually to get a specific version that works with that_style.
before_install:
  - ./docs/install-doxygen.sh

script:
  - python setup.py doc --doxygen=$TRAVIS_BUILD_DIR/doxygen/build/bin/doxygen

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
